### ISSUE TITLE
Wrong translation of index for mixed-type arrays

### ISSUE THREAD

**Issue by Oleg-N-Cher** [jtempl/ofront#46]
**GameHunter** reports:

```
MODULE Test;

TYPE
  Arr = ARRAY OF ARRAY 4 OF INTEGER;

PROCEDURE Ex ( VAR a: Arr );
  BEGIN
    a[0,1]:= -1
  END Ex;

END Test.
```

```
typedef
	INTEGER *Test_Arr[4];

static void Test_Ex (INTEGER *a, LONGINT a__len)
{
	a[0][1] = -1;
}
```

Ofront swears at the two-dimensional array index, which is passed as a pointer, i.e., a one-dimensional array. The type of mixed array is calculated incorrectly here, which is a mixture of Array and DynArr types, and, accordingly, indexing is incorrect because the array is partially dynamic, and the index must be calculated using Horner schema.

I propose this fix in the procedure OPV.design:

![image](https://user-images.githubusercontent.com/1090608/152078289-667951ef-ad07-4f29-b773-548deac56a81.png)

![image](https://user-images.githubusercontent.com/1090608/152078376-67347352-2ca8-4c48-b862-90e816052684.png)

**Comment by Oleg-N-Cher** [comment]
Oh, this my fix brokes the work of such code:

```
MODULE Ex;

TYPE
  FixedArr = ARRAY 5 OF INTEGER;

PROCEDURE Ex0 ( VAR a: INTEGER );
END Ex0;

PROCEDURE Ex3 ( VAR a: ARRAY OF FixedArr );
  BEGIN
    Ex0 ( a[ 0, 0 ] );
  END Ex3;

END Ex.
```

```
MODULE Ex;

TYPE
  FixedArray = ARRAY 5 OF INTEGER;

PROCEDURE Ex3 ( VAR a: ARRAY OF FixedArray );
  BEGIN
    a[ 0, 0 ] := a[ 0, 0 ] + 1;
  END Ex3;

END Ex.
```


Josef, I'm afraid it's a problem of the kind that I can't manage without you. Do you have a good way of determining when the Horner schema should be used to calculate the index and when it should not?

P.S. I commited this way (checking strobj = NIL), but it does not work properly for all cases. Please help!

• https://github.com/Oleg-N-Cher/OfrontPlus/commit/a8bfcd9968ea3c7612ca0a4607f5103a55f90ae7

**Comment by jtempl** [comment]
I don't remember the details, so I have to look it up in the sources.

- Josef

Oleg N. Cher ***@***.***> schrieb am Fr., 4. Feb. 2022, 03:49:

**Comment by jtempl** [comment]
Dear Oleg

in my implementation the idea of the Horner schema is applied to the
pointer arithmetics within dynamic array dimensions.
In other words, I was trying to remove common subexpressions when
calculating the number of elements per dynamic array dimension.
In C (prior to C99) there is no concept of dynamic arrays, so you declare
it as a pointer to the element type and you do the indexing
within the dynamic dimensions by pointer arithmetics.

If you have a procedure P(VAR a: ARRAY OF ARRAY OF ARRAY OF FixedArray)
with
FixedArray = ARRAY 10, 20 OF CHAR, accessing an atomic element a[i, j, k,
4, 5] would be translated to:

a[ *k* + a__len2 * ( *j* + a__len1 * *i* ) ] [4], [5]   // two additions, 2
multiplications

k + a__len2 * ( j + a__len1 * i )
=
k + a__len2 * j + a__len2 * a__len1 * i  // two additions, 3 multiplications

Applying the idea of the Horner schema as opposed to the naive pointer
arithmetics saves a multiplication here.
It saves more and it is very instructive when applied to a higher number of
dimensions.

In addition, there is an index check per dimension by means of the macro
__X(), but this has nothing to do with the pointer arithmetics.

Since this part of ofront was rather subtle, it is quite possible that
there are some special cases where it does not work as intended but the
basic idea should be correct.

- Josef


Am Fr., 4. Feb. 2022 um 03:49 Uhr schrieb Oleg N. Cher <
***@***.***>:

**Comment by Oleg-N-Cher** [comment]
Please take look to the code from the first comment. It seems that the check for typ.comp = DynArr didn't work quite right in this case. Checking the whole chain of indices for = DynArr does not give correct result either. I'm confused, because I don't understand this very well...

**Comment by Oleg-N-Cher** [comment]
For that specific case the such correction works:

![image](https://user-images.githubusercontent.com/1090608/152664790-be9b8c0d-1987-4a67-aa63-6cc2713cce1c.png)

But I'm not at all sure that this is the right fix, and that it will always work correctly...

**Comment by jtempl** [comment]
I think the problem in the original example is the anonymous element type of the open array. If I use a named element type it generates the right parameter type. With the anonymous element type one dimension is lost.
But how can such a construct be called in the first place? Doesn't it always generate a typing error because of a type mismatch of the fixed size array?

**Comment by Oleg-N-Cher** [comment]
It does not generate a typing error. I've checked it in BlackBox too, it compiles there.

Perhaps this means a dynamically allocated two-dimensional array whose second dimension is always 4 ?

**Comment by jtempl** [comment]
BlackBox has slightly relaxed typing rules, which, I guess, explains the problem. I would look at the place where the formal parameters are output. Here it should not output INTEGER *a but INTEGER[4] * a, i.e. the complete element type.

**Comment by Oleg-N-Cher** [comment]
I found the place (OPC.DeclareBase) to put the array's bracketed index. But I still don't understand how the condition should be defined to not to broke the code.

![image](https://user-images.githubusercontent.com/1090608/154207912-43871097-93fb-43a7-a815-ff640bcf68d8.png)

It is also possible to declare at C-level an anonymous type as "typedef" declaration. What would be better?

**Comment by Oleg-N-Cher** [comment]
Very cautiously I suggest such a correction. I'm not so sure about it, especially when working with more multidimensional arrays. But nothing seems to be broken. Any comments?

![image](https://user-images.githubusercontent.com/1090608/155078074-a86e7173-341b-419f-a8ce-7890194f9381.png)

• https://github.com/Oleg-N-Cher/OfrontPlus/commit/599766da106400a0a08ec76d7376a0031496a251

**Comment by Oleg-N-Cher** [comment]
It looks like the bad fix again. Josef, you see how hard it is for me.

So, Ofront already has code that outputs brackets with an array index. So I just duplicated this functionality, and not quite correctly.

OPC.DeclareObj:

![image](https://user-images.githubusercontent.com/1090608/155266605-0f0fcef2-5ea8-4444-bd53-8e9e0d4978aa.png)

If you remove this EXIT, the C code for the example in the very first post that gives the error code, with a mixed-type array begins to generate correctly. But this modification, of course, breaks the correct generation of the other code. Thus, it seems to me that the correction should simply update logics of this exit condition. We need to complicate the condition by checking for such a mixed-type array, so that the exit does not happen.

I would be glad if you could give me a hint. This is already the exact location of the error. It couldn't be more exact.

**Comment by Oleg-N-Cher** [comment]
Supplemented test example (to check that it works both with type alias and anonymously):

```
MODULE Test;

TYPE
  Arr = ARRAY OF ARRAY 4 OF INTEGER;

PROCEDURE Ex ( VAR a: Arr );
  BEGIN
    a[0,1]:= -1
  END Ex;

PROCEDURE Ex2 ( VAR a: ARRAY OF ARRAY 4 OF INTEGER );
  BEGIN
    a[0,1]:= -1
  END Ex2;

END Test.
```

**Comment by Oleg-N-Cher** [comment]
Now I propose this correction:

![image](https://user-images.githubusercontent.com/1090608/155269582-c6e81d73-334c-4d21-8908-7e24e62255d0.png)

**Comment by Oleg-N-Cher** [comment]
But this fix is not quite right either, it causes a failure when rebuilding Ofront.

**Comment by Oleg-N-Cher** [comment]
• https://github.com/Oleg-N-Cher/OfrontPlus/commit/bd890d68c5d6cb2a3193711b89eb95d0d47c429e
